// Generated by CoffeeScript 1.9.3
(function() {
  var _;

  _ = require('lodash');

  module.exports = require('./common/gwt')({
    sharedContext: true,
    defaults: {
      multipleIt: true
    },
    proxyResult: true
  });

}).call(this);
